### ISSUE TITLE
 "registeredUserContactListCall": true, causing all type of errors

### ISSUE THREAD

**Issue by kherlopian1** [AppLozic/Applozic-Android-SDK#320]
Here is whats happening, when i go to contact list . ( click chat on top, then the + icon). I get all contacts list ( say 20), when i scroll to the 20th it gives me progress loader ( loading please wait). and it keeps popping up and popping off. once i reach the end of scroll, i am stuck with this popup coming up and down. it keeps most probably calling the contacts api forever.

**Comment by kherlopian1** [comment]
https://www.dropbox.com/s/8wxc3vbnbmibqfu/Untitled.mov?dl=0

**Comment by mhrpatel12** [comment]
which SDK version you are using?

**Comment by kherlopian1** [comment]
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
     implementation project(':mobicomkitui') //Note: use this for customization
   //implementation 'com.applozic.communication.uiwidget:mobicomkitui:5.6.7'
    compile 'com.applozic.communication.uiwidget:mobicomkitui:5.6.7'
    implementation 'com.android.support:support-v4:27.1.0'
    implementation 'com.android.support:appcompat-v7:27.1.0'
    //implementation 'com.facebook.android:facebook-android-sdk:4.1.0'
    implementation 'com.android.support:design:27.1.0'
    implementation 'com.android.support:multidex:1.0.2'
    //implementation 'com.android.support:cardview-v7:22.0'
    //implementation 'com.android.support:recyclerview-v7:22.0'
    implementation('com.crashlytics.sdk.android:crashlytics:2.5.7@aar') {
        transitive = true;
    }
}


5.6.7

**Comment by mhrpatel12** [comment]
This bug is fixed in latest version. Use version 5.7

**Comment by kherlopian1** [comment]
the bug still happens if i click new broadcast from the menu options, instead of add icon.

**Comment by mhrpatel12** [comment]
we will include fix for this in an upcoming release.

**Comment by Sunilkumarr** [comment]
it has been fixed in v 5.8 you can use the latest sdk 
 ```compile 'com.applozic.communication.uiwidget:mobicomkitui:5.8```

and documentation   [link](https://docs.applozic.com/docs/android-chat-sdk#section-adding-applozic-to-existing-chat)
